<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Unity\Code.Shared.csproj">
      <Private></Private>
      <CopyLocalSatelliteAssemblies></CopyLocalSatelliteAssemblies>
    </ProjectReference>
    <ProjectReference Include="..\..\Unity\Plugins.csproj" />
  </ItemGroup>

</Project>
