<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <BaseOutputPath>D:\Documents\GitHub\MoeFight\Unity\Temp\Bin</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Code.Shared">
      <HintPath>..\..\Unity\Library\ScriptAssemblies\Code.Shared.dll</HintPath>
    </Reference>
    <Reference Include="Plugins">
      <HintPath>..\..\Unity\Library\ScriptAssemblies\Plugins.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
